version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - ./data/mysql:/var/lib/mysql:cached
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=phone_book_db
            - MYSQL_USER=phone_book_user
            - MYSQL_PASSWORD=root
        ports:
            - '33066:3306'
